site_name: easytrader
nav:
  - 简介: index.md
  - 安装: install.md
  - 使用: usage.md
  - miniqmt 量化接口: miniqmt.md
  - 雪球组合模拟交易: xueqiu.md
  - 远端服务模式: remote.md
  - 策略跟踪: follow.md
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
